import fs from 'node:fs';
import path from 'node:path';
import { builtinModules, createRequire } from 'node:module';
import { build, context } from 'esbuild';
const require = createRequire(import.meta.url);
const worker = fs.readFileSync(require.resolve('pdfjs-dist/legacy/build/pdf.worker.mjs'), 'utf8');
if (!/version:\s*['"]3\.45\.1['"]/.test(worker)) throw new Error('Review the embedded core-js version and upstream license before updating PDF.js.');
fs.mkdirSync('src/generated', { recursive: true });
fs.writeFileSync('src/generated/pdf-worker.js', `// Generated from locked pdfjs-dist; do not edit.\nmodule.exports = ${JSON.stringify(worker)};\n`);
if (process.argv.includes('--worker-only')) process.exit(0);
const options = {
  entryPoints: ['src/main.js'], bundle: true, format: 'cjs', platform: 'node', target: 'es2022',
  outfile: process.argv.includes('--watch') ? 'main.js' : '.local-backup/build/main.js', minify: true, sourcemap: false, legalComments: 'inline',
  external: ['obsidian', 'electron', ...builtinModules, ...builtinModules.map(name => `node:${name}`)],
  banner: { js: '/* Screen & File Q&A — MIT. Bundled dependency notices follow. */' },
  metafile: true
};
if (process.argv.includes('--watch')) {
  const watcher = await context(options); await watcher.watch();
  console.log('Watching plugin source. Reload the plugin in Obsidian after changes.');
} else {
  const result = await build(options);
  fs.mkdirSync('dist', { recursive: true });
  fs.writeFileSync('dist/build-meta.json', JSON.stringify(result.metafile, null, 2));
  // Include complete license texts in the standard main.js asset as well as the manual ZIP.
  const notices = [];
  const names = new Set(['pdf-parse', 'pdfjs-dist', 'core-js']);
  for (const input of Object.keys(result.metafile.inputs)) {
    const match = input.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/);
    if (match) names.add(match[1]);
  }
  const rows = [];
  for (const name of [...names].sort()) {
    const root = path.join('node_modules', name);
    if (!fs.existsSync(path.join(root, 'package.json'))) {
      if (name === 'core-js') {
        const license = fs.readFileSync('licenses/upstream/core-js-3.45.1-LICENSE', 'utf8');
        rows.push('- core-js@3.45.1 — MIT (embedded by PDF.js)');
        notices.push(`core-js@3.45.1\n${license}`);
      }
      continue;
    }
    const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
    rows.push(`- ${pkg.name}@${pkg.version} — ${pkg.license || 'see upstream license'}`);
    const licenseFiles = fs.readdirSync(root).filter(file => /^(license|licence|notice|copyright|copying)(\.|$|[-_])/i.test(file));
    const upstream = path.join('licenses/upstream', `${name.replace(/[/@]/g, '_')}-${pkg.version}-LICENSE`);
    if (!licenseFiles.length && fs.existsSync(upstream)) {
      notices.push(`${pkg.name}@${pkg.version}\n${fs.readFileSync(upstream, 'utf8')}`);
      continue;
    }
    if (!licenseFiles.length) throw new Error(`Missing license text for ${name}`);
    for (const file of licenseFiles) {
      const text = fs.readFileSync(path.join(root, file), 'utf8');
      const target = `${name.replace(/[/@]/g, '_')}-${file}`;
      fs.mkdirSync('licenses/bundled', { recursive: true });
      fs.writeFileSync(path.join('licenses/bundled', target), text);
      notices.push(`${pkg.name}@${pkg.version} / ${file}\n${text}`);
    }
  }
  fs.appendFileSync(options.outfile, '\n/*!\n' + notices.join('\n\n').replace(/\*\//g, '* /') + '\n*/\n');
  fs.copyFileSync(options.outfile, 'main.js');
  fs.writeFileSync('THIRD_PARTY_LICENSES.md', '# Bundled dependencies\n\nGenerated by `npm run build` from the locked dependencies and the actual bundle inputs.\n\n' + rows.join('\n') + '\n\nComplete license and NOTICE texts are included in `main.js` and `licenses/bundled/`. The manual installation ZIP includes that directory. No separate worker file is required.\n');
  console.log(`Built main.js (${fs.statSync('main.js').size} bytes), including the PDF worker and license notices.`);
}
